max_width = 100
hard_tabs = true
newline_style = "Unix"
reorder_imports = false
reorder_modules = true
remove_nested_parens = true
fn_args_layout = "Compressed"
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
