[package]
name = "Murasaki"
version = "0.1.0"
edition = "2018"
readme = "README.md"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dependencies.gtk]
version = "0.2"
package = "gtk4"