name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          profile: minimal
          override: true

      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check


  test:
    name: Test
    needs: [style]
    runs-on: ubuntu-latest
    
    container:
      image: ubuntu:hirsute
      options: --privileged

    strategy:
      matrix:
        build: [stable, beta, nightly]
        include:
          - build: beta
            rust: beta
          - build: nightly
            rust: nightly
            benches: true

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install curl
        run: apt update && apt install -y curl wget sudo 

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust || 'stable' }}
          profile: minimal
          override: true
      - name: Install deps
        run: sudo apt update && sudo apt-get install -y libgtk-3-dev libcairo-5c-dev libglib2.0-dev libwebkit2gtk-4.0-dev

      - name: Build debug
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.features }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.features }}

      - name: Test all benches
        if: matrix.benches
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --benches ${{ matrix.features }}

  # Publish latest and releases (e.g. tags with semver) on dockerhub.
  #  docker-push-release-latest:
  #    needs: [test]
  #    runs-on: ubuntu-latest
  #    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
  #    steps:
  #      - uses: actions/checkout@master
  #      - name: Publish to Registry
  #        uses: elgohr/Publish-Docker-Github-Action@master
  #        with:
  #          name: federicoponzi/horust
  #          username: ${{ secrets.DOCKER_USERNAME }}
  #          password: ${{ secrets.DOCKER_PASSWORD }}
  #          tag_names: true

